version: "3.9"
services:
  apache-webserver:
    image: projectfndev/fn-qa-docker-images:$newtag
    container_name: apache_
    deploy:
      replicas: 3
      resources:
            limits:
              cpus: "0.50"
              memory: "50M"
            reservations:
              cpus: "0.25"
              memory: "25M"
    ports:
      - "80:80"
        #volumes:
      # - htmldata: /var/www/localhost/htdocs
    healthcheck:
       test: curl --fail http://localhost:80 || exit 1
       interval: 60s
       retries: 5
       start_period: 20s
       timeout: 10s

volumes:
  htmldata:
